#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export N_PREFIX=$HOME

source $HOME/.rvm/scripts/rvm

# Golang

export GOPATH="$HOME/code/go"
export GOBIN="$GOPATH/bin"
export GOROOT="/s/homebrew/opt/go/libexec"

# PATH

export PATH=/usr/local/opt/qt@5.5/bin:$PATH
export PATH=$HOME/Library/Haskell/bin:$PATH
export PATH=/s/homebrew/bin:$HOME/bin:/usr/local/bin:$PATH
export PATH="$PATH:$GOPATH/bin:$GOROOT/bin"
export PATH="$HOME/.yarn/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"


export PATH="$HOME/installations/istio-1.0.1/bin:$PATH"

# Google Cloud

GOOGLE_CLOUD="$HOME/installations/google-cloud-sdk"

source "$GOOGLE_CLOUD/path.zsh.inc"
source "$GOOGLE_CLOUD/completion.zsh.inc"
# rvm

# Add RVM to PATH for scripting. This must be the last PATH variable change.
export PATH="$HOME/.rvm/bin:$PATH"

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

export FZF_DEFAULT_COMMAND='fd -t f'
export FZF_COMPLETION_TRIGGER=''
