load_module() {
  if [[ -s "$1" ]]; then
    source "$1"
  else
    echo "Could not load module '$1'"
  fi
}

load_toplevel_module() {
  load_module "${ZDOTDIR:-$HOME}/.zprezto/$1"
}

# Source Prezto.
load_toplevel_module 'init.zsh'

load_toplevel_module 'alias/init.zsh'
load_toplevel_module 'function/init.zsh'

# FZF

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export FZF_DEFAULT_COMMAND='fd'
export FZF_COMPLETION_TRIGGER=''
bindkey '^P' fzf-completion
bindkey '^I' $fzf_default_completion

_fzf_compgen_path() {
  rg --files "$1" | with-dir "$1"
}

_fzf_compgen_dir() {
  rg --files "$1" | only-dir "$1"
}

# Golang

export GOPATH="$HOME/code/go"
export GOBIN="$GOPATH/bin"
export GOROOT="/s/homebrew/opt/go/libexec"

# PATH

export PATH=$HOME/Library/Haskell/bin:$PATH
export PATH=/s/homebrew/bin:$HOME/bin:/usr/local/bin:$PATH
export PATH="$PATH:$GOPATH/bin:$GOROOT/bin"
export PATH="$HOME/.yarn/bin:$PATH"

# rvm

# # Add RVM to PATH for scripting. This must be the last PATH variable change.
export PATH="$HOME/.rvm/bin:$PATH"
source $HOME/.rvm/scripts/rvm
